### ISSUE TITLE
deletion_protection added in 0.20.0 now requires AWS provider V4.38

### ISSUE THREAD

**Issue by gchristidis** [lgallard/terraform-aws-cognito-user-pool#105]
deletion_protection to the aws_cognito_user_pool resource was released in V4.38, so the aws provider version needs to be set to '>= 4.38' or deletion_protection should be removed removed to remain compatible with '>= 3.2'.

**Comment by lgallard** [comment]
@gchristidis thanks for reporting the issue. This was fixed in the [latest release](https://github.com/lgallard/terraform-aws-cognito-user-pool/releases/tag/0.20.1)
