### ISSUE TITLE
Unable to find "Self-service sign-up" option in the module

### ISSUE THREAD

**Issue by navindu-INS** [lgallard/terraform-aws-cognito-user-pool#128]
![image](https://github.com/lgallard/terraform-aws-cognito-user-pool/assets/149157596/a0876c81-573b-4a36-b25b-3d135d2cdf84)

Hi,  can i please know how do i enable the above option using this TF module? 

Thanks!

**Comment by omar-khaled-mahmoud** [comment]
same issue

**Comment by omar-khaled-mahmoud** [comment]
add this     allow_admin_create_user_only = false  in module

**Comment by purohit14** [comment]
@omar-khaled-mahmoud @lgallard As per this documentation https://registry.terraform.io/modules/lgallard/cognito-user-pool/aws/0.29.0

There is no attribute named "allow_admin_create_user_only = true". 

The closest attribute with a similar name is "admin_create_user_config_allow_admin_create_user_only = 'true or false'"

I used the one mentioned in the documentation and this worked. Thanks.

**Comment by lgallard** [comment]
@navindu-INS @omar-khaled-mahmoud @purohit14 can you confirm it worked for you?  Otherwise, can I close this issue?

**Comment by lgallard** [comment]
Closing this issue. In case you need anything else, please let me know
