### ISSUE TITLE
Support software_token_mfa_configuration

### ISSUE THREAD

**Issue by jfharden** [lgallard/terraform-aws-cognito-user-pool#13]
It would be good to enable support for software_token_mfa_configuration so MFA can be enabled for software TOTP generators (like google authenticator, or authy).

It only needs this adding https://www.terraform.io/docs/providers/aws/r/cognito_user_pool.html#software-token-mfa-configuration so I'll submit a PR shortly

Finally great module :) Thanks!

**Comment by lgallard** [comment]
Thanks for the PR and for using and contributing to the module.

**Comment by lgallard** [comment]
@jfharden release 0.4.0 has your changes. Thanks again!!
