### ISSUE TITLE
Missing an important output for the cognito domain

### ISSUE THREAD

**Issue by catrielg** [lgallard/terraform-aws-cognito-user-pool#137]
The "aws_cognito_user_pool_domain" resource has an attribute named "[cloudfront_distribution_zone_id](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_pool_domain#cloudfront_distribution_zone_id)". This is required if you want to create a route_53 record in Terraform or other SDK. 

Suggested fix to add to the outputs.tf:
```terraform
output "domain_cloudfront_distribution_zone_id" {
  description = "The ZoneID of the CloudFront distribution"
  value       = var.enabled ? join("", aws_cognito_user_pool_domain.domain.*.cloudfront_distribution_zone_id) : null
}
```

**Comment by lgallard** [comment]
@catrielg Add in [0.27.0](https://github.com/lgallard/terraform-aws-cognito-user-pool/releases/tag/0.27.0) release.

Thanks for bring it up!
