### ISSUE TITLE
device_configuration keeps updating in place

### ISSUE THREAD

**Issue by seancarr26** [lgallard/terraform-aws-cognito-user-pool#154]
Everytime terraform apply is run, device_configuration has to be updated in place.
I have no device_configuration in the module settings

![Screenshot 2024-09-24 141526](https://github.com/user-attachments/assets/d00d905a-91ff-4612-9d0f-e7d6d2036f9b)

**Comment by joelgaria** [comment]
I have made some modifications to address the reported issue. Here are the details of the changes made in the main.tf file:

```
dynamic "device_configuration" {
  for_each = local.device_configuration
  content {
    challenge_required_on_new_device      = lookup(device_configuration.value, "challenge_required_on_new_device")
    device_only_remembered_on_user_prompt = lookup(device_configuration.value, "device_only_remembered_on_user_prompt")
  }
}
```
Additionally, I updated the following section:

```
device_configuration = var.device_configuration == null ? [] : [{
    challenge_required_on_new_device      = lookup(var.device_configuration, "challenge_required_on_new_device", var.device_configuration_challenge_required_on_new_device)
    device_only_remembered_on_user_prompt = lookup(var.device_configuration, "device_only_remembered_on_user_prompt", var.device_configuration_device_only_remembered_on_user_prompt)
}]
```
In the variables.tf file, I defined the device_configuration variable as follows:
```
# device_configuration
variable "device_configuration" {
  description = "Configuration for devices"
  type        = map(string)
  default     = null
}
```
I hope these changes contribute to resolving the reported issue. I look forward to your feedback.

**Comment by seancarr26** [comment]
Thanks. When will these changes be available in the module?

**Comment by seancarr26** [comment]
Thank you. Appreciate it.

**Comment by lgallard** [comment]
@seancarr26 I'm closing this issue as release [0.32.0](https://github.com/lgallard/terraform-aws-cognito-user-pool/releases/tag/0.32.0) fixes it.

If you have any comment, suggestions or doubts, just let me know.
