### ISSUE TITLE
AccountRecoverySetting not supported

### ISSUE THREAD

**Issue by laandes** [lgallard/terraform-aws-cognito-user-pool#17]
AccountRecoverySetting with the RecoveryMechanisms "admin_only" , "verified_email" and  "verified_phone_number" is not supported. Should be able to set 1 or two with priority 1 & 2.
The deployment will default to  the only "Not recommended" setting - Phone if available, otherwise email, and do allow a user to reset their password via phone if they are also using it for MFA. 
ps. otherwise a very nice module, thanks for sharing it.

**Comment by lgallard** [comment]
@laandes thanks for your feedback. Can you tell me if it's not supported by my module or by Terraform's provider?

**Comment by laandes** [comment]
Thanks for getting back. This is an excellent question. I'm new to terraform and looking at the provider I can't find the AccountRecoverySetting there either.

**Comment by lgallard** [comment]
@laandes can you share a snippet with your Terraform configuration?

**Comment by Xumeiquer** [comment]
I'd like to recover this issue as it is still missing. The feature is missing in your module @lgallard. Terraform implements it here https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_pool#using-account-recovery-setting

**Comment by lgallard** [comment]
Thanks @Xumeiquer for point it out. I will include as soon as I can implemented or if you already had some code, you can share it thru a PR.

**Comment by lgallard** [comment]
@Xumeiquer PR #32 includes this setting.
