### ISSUE TITLE
username_configuration case_sensitive

### ISSUE THREAD

**Issue by Modestasthinkt** [lgallard/terraform-aws-cognito-user-pool#20]
Cannot use terraform import with module it always forces replacement. 
If i remove this line:  `  username_configuration {
    case_sensitive = var.case_sensitive
  }` from main.tf it works fine.

**Comment by lgallard** [comment]
@Modestasthinkt try defining 'case_sensitive' with the same value it tries to replace.

**Comment by bentlema** [comment]
Even with the same value, terraform wants to force replacement because the entire username_configuration block is absent (it's optional and the resource was originally provisioned via the console).  Would converting username_configuration to a dynamic block solve this?

**Comment by lgallard** [comment]
@Modestasthinkt @bentlema I couldn't reproduce the issue. I created a new user pool from the console and then imported with Terraform. 

Can you give me more information? 

-  AWS provider version?
- Terraform version?

**Comment by lgallard** [comment]
@bentlema I can add the suggested code, but `username_configuration` is just one bock definition.

**Comment by bentlema** [comment]
In my case, I'm using:  Terraform v0.12.29, provider.aws v2.70.0

About that code snippet: I was just looking for a way to omit the username_configuration block entirely and it seems like the dynamic block achieves that when given an empty list, but I didn't spend too much time on it...could be a better way I'm missing.

Also, I had imported a user pool that was created over a year ago.  Let me see if it does the same thing with a new pool...

**Comment by lgallard** [comment]
@eduzera I see...I'm adding you code to avoid defining `username_configuration`

**Comment by bentlema** [comment]
Yeah, same here, I was unable to repo on a newly-created user pool via the console.

But, I did find a case where I could repo the issue:
1.  Create a new user pool via terraform using resource aws_cognito_user_pool directly
2.  Build out a new root module using [this](https://github.com/lgallard/terraform-aws-cognito-user-pool) module & import the pool created in the previous step
3. Run a terraform plan, and you'll see that it wants to destroy/re-create due to the case_sensitive option

**Comment by lgallard** [comment]
@bentlema you can try with this branch https://github.com/lgallard/terraform-aws-cognito-user-pool/tree/dynamic_username_configuration_block

If you omit the `user_configuration` variable it shouldn't create the block (I used you code and jus rename the local).

If it works for you, I merge it after updating the README and the examples.

**Comment by bentlema** [comment]
Thanks @lgallard !  Tested it, and works great.

**Comment by lgallard** [comment]
@Modestasthinkt @bentlema release 0.6.0 fixes this issue!
