### ISSUE TITLE
Support email_configuration.from_email_address field

### ISSUE THREAD

**Issue by miran248** [lgallard/terraform-aws-cognito-user-pool#26]
[email_configuration](https://github.com/lgallard/terraform-aws-cognito-user-pool/blob/master/main.tf#L50) is missing [from_email_address](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_pool#from_email_address) declaration.

```
from_email_address  = lookup(email_configuration.value, "from_email_address")
```

**Comment by lgallard** [comment]
@miran248 First off, thanks for reporting the optional field.

On the other hand, If you can check / test PR #27 I'll merge it immediately.

Regards!

**Comment by miran248** [comment]
Just tried it and it didn't work.

There's a small typo on line 54
https://github.com/lgallard/terraform-aws-cognito-user-pool/blob/ce86e85d422e4ecd2510c1e6ab7538a6940b1c84/main.tf#L54

`from_email_address     = lookup(from_email_address.value, "from_email_address")`
should be
`from_email_address     = lookup(email_configuration.value, "from_email_address")`

Everything else looks fine.

Thanks!

**Comment by lgallard** [comment]
@miran248 typo fixed! Can you try it again, please?

**Comment by miran248** [comment]
It's working! Thank you

**Comment by lgallard** [comment]
Great! Thanks @miran248  for confirming it's working!!
