### ISSUE TITLE
Error: Instance cannot be destroyed

### ISSUE THREAD

**Issue by jigneshpatel7** [lgallard/terraform-aws-cognito-user-pool#30]
.\terraform.exe destroy

Error: Instance cannot be destroyed

   1: resource "aws_cognito_user_pool" "pool" {

Resource module.aws_cognito_user_pool_complete.aws_cognito_user_pool.pool has
lifecycle.prevent_destroy set, but the plan calls for this resource to be
destroyed. To avoid this error and continue with the plan, either disable
lifecycle.prevent_destroy or reduce the scope of the plan using the -target
flag.

**Comment by lgallard** [comment]
@jigneshpatel7 the changes to be ignore are related to the `schema`  https://github.com/lgallard/terraform-aws-cognito-user-pool/blob/master/main.tf#L182 

Do you have any other case?

**Comment by jigneshpatel7** [comment]
no, Thanks
