### ISSUE TITLE
support account_recovery_setting

### ISSUE THREAD

**Issue by hyei** [lgallard/terraform-aws-cognito-user-pool#31]
Please support the account_recovery_setting in the module. It is not a valid input for the module, but even when left at the defaults, Terraform detects a change:

Terraform 0.14.3 
hashicorp/aws v3.22.0 

[output]
Terraform will perform the following actions:

  # module.cognito_jams_prod.aws_cognito_user_pool.pool will be updated in-place
  ~ resource "aws_cognito_user_pool" "pool" {
        id                         = "XXXXXXX"
        name                       = "XXXXXXX"
        tags                       = {
            "Terraform"   = "1"
        }
        # (10 unchanged attributes hidden)

      - account_recovery_setting {
        }

**Comment by lgallard** [comment]
@hyei check the PR https://github.com/lgallard/terraform-aws-cognito-user-pool/pull/32

In particular, the branch `feature/account_recovery_setting` has the following code 
https://github.com/lgallard/terraform-aws-cognito-user-pool/blob/feature/account_recovery_setting/main.tf#L178:
```
  # account_recovery_setting
  dynamic "account_recovery_setting" {
    for_each = lenght(var.recovery_mechanisms) == 0 ? [] : [1]
    content {
      # recovery_mechanism
      dynamic "recovery_mechanism" {
        for_each = var.recovery_mechanisms
        content {
          name     = lookup(recovery_mechanism.value, "name")
          priority = lookup(recovery_mechanism.value, "priority")
        }
      }
    }
  }
```

Which is triggered if you define the variable `recovery_mechanisms` with some settings (put yours as needed):

```
  recovery_mechanisms = [
     {
      name     = "verified_email"
      priority = 1
    },
    {
      name     = "verified_phone_number"
      priority = 2
    }
  ]

```

It's no tested, I just write the code. If you can check it and give me  feedback, it would be awesome. If you can't I'll do it as soon as I can (maybe this  year).

**Comment by lgallard** [comment]
Fixed by PR https://github.com/lgallard/terraform-aws-cognito-user-pool/pull/32
