### ISSUE TITLE
The default value for the new enabled field in version 0.9.0 should be true

### ISSUE THREAD

**Issue by gchristidis** [lgallard/terraform-aws-cognito-user-pool#36]
Is there any reason to making enabled default to false ?  This makes it an incompatible upgrade without changing the calling module, anyone upgrading from a previous version of this module on an existing Terraform state might be surprised when they lose their pool !

In addition in this state the documentation is wrong, the enable flag is marked as optional but this is incorrect, it must be supplied to create the pool, also the examples (simple & complex) need to have the enabled = true added.

Can I suggest the default be true, that way nothing needs to change.

Thanks

**Comment by lgallard** [comment]
@gchristidis thanks for reporting the issue. I released version 0.9.1 with the fix.

Regards!

**Comment by gchristidis** [comment]
Thanks for the quick turn around

**Comment by lgallard** [comment]
@gchristidis you are welcome!
