### ISSUE TITLE
How to setup UserPool for Email address or phone number like the dashboard setup?

### ISSUE THREAD

**Issue by duanvnc** [lgallard/terraform-aws-cognito-user-pool#41]
Hi guys, I just want to switch the option to this one:
Email address or phone number - Users can use an email address or phone number as their "username" to sign up and sign in.

So, which set up in your code could do that?

Image: https://prnt.sc/xve7mq

Thanks,

**Comment by lgallard** [comment]
HI @duanvnc, you can use the `alias_attributes` variable:
```
alias_attributes = [ "phone_number", "email" ]
```
Please refere to the Terraform documentation for the resource
 https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_pool#alias_attributes

>  alias_attributes - (Optional) Attributes supported as an alias for this user pool. Possible values: phone_number, email, or preferred_username. Conflicts with `username_attributes`.
