### ISSUE TITLE
Resource servers, custom scopes and missing depends_on

### ISSUE THREAD

**Issue by MichaelVL** [lgallard/terraform-aws-cognito-user-pool#51]
When creating user pools with a client and resource servers and adding the resource server to the client as a custom scope, e.g:

```
module "cognito_user_pool" {
  source  = "lgallard/cognito-user-pool/aws"
  ...
  resource_servers = [
    {
      identifier = "https://foo.bar"
      scope = [
        {
          scope_name = "api"
        }
      ]
    }
  ]
  clients = [
  {
    allowed_oauth_scopes = ["openid", "profile", "https://foo.bar/api"]
  }
}
```

Then, if `aws_cognito_user_pool_client.client` is created before `aws_cognito_resource_server.resource`, it will fail because the custom scope `https://foo.bar/api` is unknown.

I worked-around the issue with a `depends_on` in `aws_cognito_user_pool_client.client` like this:

```
resource "aws_cognito_user_pool_client" "client" {
  ...
  depends_on = [ aws_cognito_resource_server.resource ]
}
```

**Comment by lgallard** [comment]
@MichaelVL Nice catch! I will include the fix in the next release. Thanks!

**Comment by lgallard** [comment]
@MichaelVL release 0.10.4 fixes the issue!
