### ISSUE TITLE
prevent_destroy Variables may not be used here.

### ISSUE THREAD

**Issue by exocom** [lgallard/terraform-aws-cognito-user-pool#58]
Unable to plan or apple because of prevent_destroy using a variable.
See https://github.com/hashicorp/terraform/issues/22544

If you want to implement prevent_destroy you have to duplicate the entire resource. Suggest to revert until new implementation can be created.

**Comment by lgallard** [comment]
FIxed in release 0.11.1. I'll keep on eye on the provider issue. If it solved I will include @Waschnick implementation back!
