### ISSUE TITLE
Including custom attributes in tf file.

### ISSUE THREAD

**Issue by Akash76** [lgallard/terraform-aws-cognito-user-pool#60]
I am trying to include custom attributes in the main.tf file. But I am not able to do and it is not there in documentation. Is there any way to include custom attributes ?

Code:
module "userpool" {
  source  = "lgallard/cognito-user-pool/aws"
  user_pool_name = "test"
  domain = "test"
  custom_attributes = "" <--- How to include custom_attributes?
  admin_create_user_config = {
    allow_admin_create_user_only = false
  }

  clients = [
      {
          "name" = "test-client"
      }
  ]
}

**Comment by Akash76** [comment]
Modified code

**Comment by lgallard** [comment]
@Akash76 just set the name of your custom attribute:

```
  number_schemas = [
    {
      attribute_data_type      = "Number"
      developer_only_attribute = true
      mutable                  = true
      name                     = "mynumber1"
      required                 = false

      number_attribute_constraints = {
        min_value = 2
        max_value = 6
      }
    },
    {
      attribute_data_type      = "Number"
      developer_only_attribute = true
      mutable                  = true
      name                     = "mynumber2"
      required                 = false

      number_attribute_constraints = {
        min_value = 2
        max_value = 6
      }
    },
  ]
```
Please refer to the [complete example](here https://github.com/lgallard/terraform-aws-cognito-user-pool/tree/master/examples/complete) for other usages.
