### ISSUE TITLE
Add to output map of client_ids and client_secrets

### ISSUE THREAD

**Issue by dmytro-dorofeiev** [lgallard/terraform-aws-cognito-user-pool#65]
The current output client_ids and client_secrets contains a list of ids and secrets. When I need to pass client id and client secret to other resources like lambda, I have to use index like module.cognito-user-pool.client_ids[1] module.cognito-user-pool.client_secrets[1]. The index could be changed when you create new app clients, so it's hard to be sure that it always points to correct one. I'd suggest to add to output:
`output "client_ids_map" {
  description = "The ids of the user pool clients"
  value = { for k, v in aws_cognito_user_pool_client.client : v.name => v.id }
}`
`output "client_secrets_map" {
  description = " The client secrets of the user pool clients"
  value       = { for k, v in aws_cognito_user_pool_client.client : v.name => v.client_secret }
}`
In that case it would be easier to find proper app client with corresponding app secret with 
`lookup(module.cognito-user-pool.client_ids_map, "admin-client")`

**Comment by lgallard** [comment]
@dmytro-dorofeiev thanks for the suggestion I like it. I'll change it as soon as possible unless you create a PR first!

**Comment by dmytro-dorofeiev** [comment]
I've created PR. If you be able to please review.

**Comment by lgallard** [comment]
@dmytro-dorofeiev  releases 0.14.0 includes your changes. Thank you!!
