### ISSUE TITLE
Update to allow AWS provider version 4.x

### ISSUE THREAD

**Issue by domeales-paloit** [lgallard/terraform-aws-cognito-user-pool#79]
Hi there,

Great module, thanks for creating it!

Currently the module is using the paranoid operator for the version of the AWS provider, locking it to AWS provider versions 3.2 to 3.74.3 (at the time of writing). The AWS provider recently released version 4.

https://github.com/lgallard/terraform-aws-cognito-user-pool/blob/master/versions.tf#L5

Would it be possible to change this to allow versions on AWS provider 4.x, something like below?

```hcl
terraform {
  required_version = ">= 0.14.0"

  required_providers {
    aws = "~> 3.2, ~> 4.0"
  }
}
```

**Comment by lgallard** [comment]
@domeales-paloit thanks for reporting the issue. Yes, it's possible to change that. I will create the PR soon.

**Comment by lgallard** [comment]
@domeales-paloit the latest release has the fix!

**Comment by domeales-paloit** [comment]
@lgallard Great, thank you!
