### ISSUE TITLE
lambda_config keeps changing.

### ISSUE THREAD

**Issue by diepes** [lgallard/terraform-aws-cognito-user-pool#82]
In my config, i have no lambda_config variable,    also tried with lambda_config = {}

Every apply/plan i get a change

```
 # module.cognito_user_pool.aws_cognito_user_pool.pool[0] will be updated in-place
  ~ resource "aws_cognito_user_pool" "pool" {
     ...
     ...
     + lambda_config {
          + custom_email_sender {
              + lambda_arn     = (known after apply)
              + lambda_version = (known after apply)
            }

          + custom_sms_sender {
              + lambda_arn     = (known after apply)
              + lambda_version = (known after apply)
            }
        }
```

**Comment by zumby** [comment]
@Hatko & @diepes 
You can temporary comment out the whole lambda_config block in main.tf - probably, once you start using lambdas this issue will be self-resolved

_main.tf_
```
  # dynamic "lambda_config" {
  #   for_each = var.lambda_config == null && length(local.lambda_config) == 0 ? [] : local.lambda_config
  #   content {
  #     create_auth_challenge          = lookup(lambda_config.value, "create_auth_challenge")
  #     custom_message                 = lookup(lambda_config.value, "custom_message")
  #     define_auth_ch
  ...
```

**Comment by lgallard** [comment]
@zumby commenting the block doesn't fix it. The problem is in the AWS provider, not in the module.  In fact, there is an [open issue](https://github.com/hashicorp/terraform-provider-aws/issues/19942) reported at the Terraform AWS provider repo that describes this behaviour.

**Comment by lgallard** [comment]
@diepes @Hatko @zumby [Release 0.16.0](https://github.com/lgallard/terraform-aws-cognito-user-pool/tree/0.16.0) fixes the issue.
