### ISSUE TITLE
String schema issue

### ISSUE THREAD

**Issue by tanjilbhuiyan** [lgallard/terraform-aws-cognito-user-pool#86]
Any kind of string schema is not creating, its showing in tfstate, but not in aws console. 

  string_schemas = [
    {
      attribute_data_type      = "String"
      developer_only_attribute = false
      mutable                  = true
      name                     = "name"
      required                 = false

      string_attribute_constraints = {
        min_length = 3
        max_length = 50
      }
    },
  ]

schemas & number_schemas are working as expected. but string schema is not working.

**Comment by lgallard** [comment]
Please refer to the string schema in the complete example [here](https://github.com/lgallard/terraform-aws-cognito-user-pool/blob/0.32.0/examples/complete/main.tf#L96).

Closing this issue now, but you are free to comment if needed.
