### ISSUE TITLE
feat: grant cognito lambda execution permissions to all functions

### ISSUE THREAD

**Issue by jeffreymlewis** [lgallard/terraform-aws-cognito-user-pool#89]
I ran into [this issue today](https://github.com/hashicorp/terraform-provider-aws/issues/8373), whereby cognito cannot execute lambda functions deployed only by terraform. Submitted this PR as a work-around. Let me know your thoughts.

https://github.com/lgallard/terraform-aws-cognito-user-pool/pull/88

**Comment by lgallard** [comment]
@jeffreymlewis as commented in #88 I'd rather to support resources and logic related to the module's functionality.
